services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=PGKing-mysql;Port=3306;Database=pgkingDb;User=pgkinguser;Password=pgkingpassword;AllowPublicKeyRetrieval=True;SslMode=None;
      - "ConnectionStrings:DefaultConnection=Server=PGKing-mysql;Port=3306;Database=pgkingDb;User=pgkinguser;Password=pgkingpassword;AllowPublicKeyRetrieval=True;SslMode=None;"
      - ASPNETCORE_URLS=http://+:8080
    depends_on:
      db:
        condition: service_healthy
    links:
      - db

  db:
    image: mysql:8.0.33
    container_name: PGKing-mysql
    command: --default-authentication-plugin=mysql_native_password --bind-address=0.0.0.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: pgkingDb
      MYSQL_USER: pgkinguser
      MYSQL_PASSWORD: pgkingpassword
    ports:
      - "3307:3306"

    expose:
      - "3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "pgkinguser", "-ppgkingpassword"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  mysql_data:




